Refactor of TestBalances to allow more general scenarios (#18)
This PR refactors the TestBalances struct to wrap a Vec<u64> -- this allows for the construction of test scenarios that have different numbers of users. It also adds an additional, three-party test scenario, and improves the interface to generate transactions within the scenario.

diff --git a/.github/workflows/zebra-test-ci.yaml b/.github/workflows/zebra-test-ci.yaml
--- a/.github/workflows/zebra-test-ci.yaml
+++ b/.github/workflows/zebra-test-ci.yaml
@@ -41,7 +41,7 @@ jobs:
         load: true
         cache-from: type=local,src=/tmp/.buildx-cache
         cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
-        
+
     - name: Run Zebra Node container
       run: |
         docker run -d --name zebra-node -p 18232:18232 zebra-node:local
@@ -49,7 +49,7 @@ jobs:
         echo "Waiting for Zebra node to initialize..."
         sleep 30
         echo "Finished waiting for Zebra node..."
-
+        
     - name: Build tx-tool
       uses: docker/build-push-action@v4
       with:
@@ -58,8 +58,8 @@ jobs:
         tags: zcash-tx-tool:local
         push: false
         load: true
-        
-    - name: Run tx-tool and verify success
+
+    - name: Run tx-tool for test-orchard-zsa and verify success
       run: |
         # Create a network to connect the containers
         docker network create zcash-net
@@ -73,10 +73,16 @@ jobs:
           -e ZCASH_NODE_PORT=18232 \
           -e ZCASH_NODE_PROTOCOL=http \
           --name zcash-tx-tool \
-          zcash-tx-tool:local
-          
+          zcash-tx-tool:local test-orchard-zsa
+        
+        echo "Printing container logs:"
+        docker logs zcash-tx-tool        
+        
         # Get the exit code from the container
         EXIT_CODE=$(docker inspect zcash-tx-tool --format='{{.State.ExitCode}}')
+        
+        # Clean up
+        docker rm zcash-tx-tool
         
         # Check if the tx_tool succeeded
         if [ $EXIT_CODE -eq 0 ]; then
@@ -84,7 +90,33 @@ jobs:
           exit 0
         else
           echo "tx-tool failed with exit code $EXIT_CODE"
-          echo "Printing container logs:"
-          docker logs zcash-tx-tool
+          exit 1
+        fi
+
+    - name: Run tx-tool again for test-three-party and verify success
+      run: |                
+        # Run the tx tool and capture exit code
+        docker run --network zcash-net \
+          -e ZCASH_NODE_ADDRESS=zebra-node \
+          -e ZCASH_NODE_PORT=18232 \
+          -e ZCASH_NODE_PROTOCOL=http \
+          --name zcash-tx-tool \
+          zcash-tx-tool:local test-three-party
+        
+        echo "Printing container logs:"
+        docker logs zcash-tx-tool
+        
+        # Get the exit code from the container
+        EXIT_CODE=$(docker inspect zcash-tx-tool --format='{{.State.ExitCode}}')
+        
+        # Clean up
+        docker rm zcash-tx-tool
+        
+        # Check if the tx_tool succeeded
+        if [ $EXIT_CODE -eq 0 ]; then
+          echo "tx-tool completed successfully!"        
+          exit 0
+        else
+          echo "tx-tool failed with exit code $EXIT_CODE"
           exit 1
         fi
